version: '3.7'

services:
  app:
    image: learning-docker/node:v2
    ports:
      - '80:3000'
    restart: unless-stopped
    networks:
      - app-network

  web:
    image: nginx:1.17-alpine
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
